apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mappings.ambassadorshim.admiralty.io
spec:
  group: ambassadorshim.admiralty.io
  version: v1alpha1
  names:
    kind: Mapping
    plural: mappings
    singular: mapping